const passwordBlacklist = (register) => {
  return [
    register.email.slice(0, 1).toUpperCase() + register.email.slice(1),
    register.email.slice(0, 1).toUpperCase() + register.email.slice(1) + "0",
    register.email.slice(0, 1).toUpperCase() + register.email.slice(1) + "1",
    register.email.slice(0, 1).toUpperCase() + register.email.slice(1) + "12",
    register.email.slice(0, 1).toUpperCase() + register.email.slice(1) + "123",
    register.email.slice(0, 1).toUpperCase() + register.email.slice(1) + "1234",
    register.email.slice(0, 1).toUpperCase() +
      register.email.slice(1) +
      "12345",
    register.fName.slice(0, 1).toUpperCase() + register.fName.slice(1) + "0",
    register.lName.slice(0, 1).toUpperCase() + register.lName.slice(1) + "0",
    register.fName.slice(0, 1).toUpperCase() + register.fName.slice(1) + "1",
    register.lName.slice(0, 1).toUpperCase() + register.lName.slice(1) + "1",
    register.fName.slice(0, 1).toUpperCase() + register.fName.slice(1) + "12",
    register.lName.slice(0, 1).toUpperCase() + register.lName.slice(1) + "12",
    register.fName.slice(0, 1).toUpperCase() + register.fName.slice(1) + "123",
    register.lName.slice(0, 1).toUpperCase() + register.lName.slice(1) + "123",
    register.fName.slice(0, 1).toUpperCase() + register.fName.slice(1) + "1234",
    register.lName.slice(0, 1).toUpperCase() + register.lName.slice(1) + "1234",
    register.fName.slice(0, 1).toUpperCase() +
      register.fName.slice(1) +
      "12345",
    register.lName.slice(0, 1).toUpperCase() +
      register.lName.slice(1) +
      "12345",
    register.fName.toLowerCase() + register.lName + "0",
    register.fName.toLowerCase() + register.lName + "1",
    register.fName.toLowerCase() + register.lName + "12",
    register.fName.toLowerCase() + register.lName + "123",
    register.fName.toLowerCase() + register.lName + "1234",
    register.fName.toLowerCase() + register.lName + "12345",
    register.fName + register.lName + "0",
    register.fName + register.lName + "1",
    register.fName + register.lName + "12",
    register.fName + register.lName + "123",
    register.fName + register.lName + "1234",
    register.fName + register.lName + "12345",
    register.fName + "0",
    register.lName + "0",
    register.fName + "1",
    register.lName + "1",
    register.fName + "12",
    register.lName + "12",
    register.fName + "123",
    register.lName + "123",
    register.fName + "1234",
    register.lName + "1234",
    register.fName + "12345",
    register.lName + "12345",
    "Senha123",
    "Senha1234",
    "Senha12345",
    "Minhasenha1",
    "Minhasenha12",
    "Minhasenha123",
    "Minhasenha1234",
    "Minhasenha12345",
    "MinhaSenha1",
    "MinhaSenha12",
    "MinhaSenha123",
    "MinhaSenha1234",
    "MinhaSenha12345",
    "Password1",
    "Password12",
    "Password123",
    "Password1234",
    "Password12345",
    "Passw0rd",
    "Passw0rd1",
    "Passw0rd12",
    "Passw0rd123",
    "Passw0rd1234",
    "Passw0rd12345",
  ];
};

export default passwordBlacklist;
